[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

[lib]
name = "adventofcode2023"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
